//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic_Student
    {
        public string ID { get; set; }
        public int Sex { get; set; }
        public string ClassID { get; set; }
        public string SpecialtyID { get; set; }
        public string StartYear { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
        public string XH { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Name { get; set; }
        public string Education { get; set; }
        public string RecentActivities { get; set; }
        public string ILike { get; set; }
        public string PersonalSign { get; set; }
        public string Dormitory { get; set; }
        public string NativePlace { get; set; }
    
        public virtual Basic_Class Basic_Class { get; set; }
        public virtual Basic_Specialty Basic_Specialty { get; set; }
        public virtual Sys_User Sys_User { get; set; }
    }
}
