//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic_OrganizeUser_Relationship
    {
        public string SchoolID { get; set; }
        public string OrganizeID { get; set; }
        public string UserID { get; set; }
    
        public virtual Basic_Organize Basic_Organize { get; set; }
        public virtual Sys_School Sys_School { get; set; }
        public virtual Sys_User Sys_User { get; set; }
    }
}
