//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic_News
    {
        public string ID { get; set; }
        public string SchoolID { get; set; }
        public string CategoryID { get; set; }
        public string DisplayType { get; set; }
        public string Subject { get; set; }
        public string PreviewImage { get; set; }
        public Nullable<int> BrowseCount { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public string Abstract { get; set; }
        public string ContentBody { get; set; }
        public Nullable<int> IsMainDisplay { get; set; }
        public Nullable<int> IsCategoryTop { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
    
        public virtual Basic_NewsCategory Basic_NewsCategory { get; set; }
        public virtual Sys_School Sys_School { get; set; }
    }
}
