//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content_Article
    {
        public Content_Article()
        {
            this.Content_ArticleSlide = new HashSet<Content_ArticleSlide>();
        }
    
        public string ID { get; set; }
        public string SchoolID { get; set; }
        public string Title { get; set; }
        public string CategoryID { get; set; }
        public string RecommendType { get; set; }
        public string CoverImage { get; set; }
        public string BrowseCount { get; set; }
        public string Digest { get; set; }
        public string SourceUrl { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public string ArticleContent { get; set; }
        public Nullable<int> IsMainDisplay { get; set; }
        public Nullable<int> IsCategoryTop { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
        public string CoverImageThumbnailRect { get; set; }
        public string CoverImageThumbnailSquare { get; set; }
    
        public virtual Content_Category Content_Category { get; set; }
        public virtual ICollection<Content_ArticleSlide> Content_ArticleSlide { get; set; }
        public virtual Sys_School Sys_School { get; set; }
    }
}
