//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content_Category
    {
        public Content_Category()
        {
            this.Content_Article = new HashSet<Content_Article>();
            this.Content_Category1 = new HashSet<Content_Category>();
        }
    
        public string ID { get; set; }
        public string SchoolID { get; set; }
        public string Name { get; set; }
        public string ParentID { get; set; }
        public Nullable<int> ContentLevel { get; set; }
        public string ContentPath { get; set; }
        public string ContentIcon { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
    
        public virtual ICollection<Content_Article> Content_Article { get; set; }
        public virtual ICollection<Content_Category> Content_Category1 { get; set; }
        public virtual Content_Category Content_Category2 { get; set; }
        public virtual Sys_School Sys_School { get; set; }
    }
}
