//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OurSolutionEntities : DbContext
    {
        public OurSolutionEntities()
            : base("name=OurSolutionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Basic_Campus> Basic_Campus { get; set; }
        public DbSet<Basic_Device> Basic_Device { get; set; }
        public DbSet<Basic_DeviceToken> Basic_DeviceToken { get; set; }
        public DbSet<Basic_Notice> Basic_Notice { get; set; }
        public DbSet<Basic_NoticeUser_Relationship> Basic_NoticeUser_Relationship { get; set; }
        public DbSet<Sys_Log> Sys_Log { get; set; }
        public DbSet<Basic_Group> Basic_Group { get; set; }
        public DbSet<Basic_GroupUser_Relationship> Basic_GroupUser_Relationship { get; set; }
        public DbSet<Basic_Organize> Basic_Organize { get; set; }
        public DbSet<Basic_OrganizeUser_Relationship> Basic_OrganizeUser_Relationship { get; set; }
        public DbSet<Sys_Feature> Sys_Feature { get; set; }
        public DbSet<Sys_Feature_Authority> Sys_Feature_Authority { get; set; }
        public DbSet<Sys_School> Sys_School { get; set; }
        public DbSet<Sys_School_Extend> Sys_School_Extend { get; set; }
        public DbSet<Sys_User> Sys_User { get; set; }
        public DbSet<Basic_TelephoneDirectory> Basic_TelephoneDirectory { get; set; }
        public DbSet<Basic_NewsCategory> Basic_NewsCategory { get; set; }
        public DbSet<Basic_Attachment> Basic_Attachment { get; set; }
        public DbSet<Message_RegisterMobile> Message_RegisterMobile { get; set; }
        public DbSet<Basic_Class> Basic_Class { get; set; }
        public DbSet<Basic_Specialty> Basic_Specialty { get; set; }
        public DbSet<Basic_Student> Basic_Student { get; set; }
        public DbSet<Basic_News> Basic_News { get; set; }
        public DbSet<Message_SchoolKeys> Message_SchoolKeys { get; set; }
        public DbSet<Sys_OtherSysInterfaceAddr> Sys_OtherSysInterfaceAddr { get; set; }
        public DbSet<Sys_SMSDetailLog> Sys_SMSDetailLog { get; set; }
        public DbSet<Sys_Config> Sys_Config { get; set; }
        public DbSet<VenuSoft_Message_NotFullRemind> VenuSoft_Message_NotFullRemind { get; set; }
        public DbSet<VenuSoft_User> VenuSoft_User { get; set; }
        public DbSet<Sys_Theme> Sys_Theme { get; set; }
        public DbSet<Sys_PushMessage> Sys_PushMessage { get; set; }
        public DbSet<Content_Article> Content_Article { get; set; }
        public DbSet<Content_ArticleSlide> Content_ArticleSlide { get; set; }
        public DbSet<Content_Category> Content_Category { get; set; }
        public DbSet<Sys_Role> Sys_Role { get; set; }
        public DbSet<Sys_Menu> Sys_Menu { get; set; }
        public DbSet<Sys_Operation> Sys_Operation { get; set; }
        public DbSet<Sys_RoleMenuOperation> Sys_RoleMenuOperation { get; set; }
        public DbSet<Basic_TeacherInfo> Basic_TeacherInfo { get; set; }
        public DbSet<Basic_TeacherInfo_Education> Basic_TeacherInfo_Education { get; set; }
        public DbSet<Basic_TeacherInfo_Experience> Basic_TeacherInfo_Experience { get; set; }
        public DbSet<Basic_TeacherInfo_Fruit> Basic_TeacherInfo_Fruit { get; set; }
        public DbSet<Basic_TeacherInfo_Practice> Basic_TeacherInfo_Practice { get; set; }
        public DbSet<Basic_TeacherInfo_Reward> Basic_TeacherInfo_Reward { get; set; }
        public DbSet<Basic_TeacherInfo_Training> Basic_TeacherInfo_Training { get; set; }
        public DbSet<Basic_Department> Basic_Department { get; set; }
        public DbSet<Basic_Hobby> Basic_Hobby { get; set; }
        public DbSet<Basic_DictCode> Basic_DictCode { get; set; }
        public DbSet<Basic_DictCodeType> Basic_DictCodeType { get; set; }
        public DbSet<Sys_School_PanelContent> Sys_School_PanelContent { get; set; }
    }
}
