//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Menu
    {
        public Sys_Menu()
        {
            this.Sys_Menu1 = new HashSet<Sys_Menu>();
            this.Sys_RoleMenuOperation = new HashSet<Sys_RoleMenuOperation>();
            this.Sys_Operation = new HashSet<Sys_Operation>();
            this.Sys_Role = new HashSet<Sys_Role>();
        }
    
        public string MenuID { get; set; }
        public string MenuName { get; set; }
        public string MenuUrl { get; set; }
        public string MenuIconClass { get; set; }
        public string MenuIconImageUrl { get; set; }
        public string ParentMenuID { get; set; }
        public Nullable<int> Depth { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
        public string SchoolID { get; set; }
    
        public virtual ICollection<Sys_Menu> Sys_Menu1 { get; set; }
        public virtual Sys_Menu Sys_Menu2 { get; set; }
        public virtual ICollection<Sys_RoleMenuOperation> Sys_RoleMenuOperation { get; set; }
        public virtual ICollection<Sys_Operation> Sys_Operation { get; set; }
        public virtual ICollection<Sys_Role> Sys_Role { get; set; }
        public virtual Sys_School Sys_School { get; set; }
    }
}
