//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_School
    {
        public Sys_School()
        {
            this.Basic_Campus = new HashSet<Basic_Campus>();
            this.Basic_DeviceToken = new HashSet<Basic_DeviceToken>();
            this.Basic_Group = new HashSet<Basic_Group>();
            this.Basic_GroupUser_Relationship = new HashSet<Basic_GroupUser_Relationship>();
            this.Basic_OrganizeUser_Relationship = new HashSet<Basic_OrganizeUser_Relationship>();
            this.Sys_Feature = new HashSet<Sys_Feature>();
            this.Sys_Feature_Authority = new HashSet<Sys_Feature_Authority>();
            this.Basic_TelephoneDirectory = new HashSet<Basic_TelephoneDirectory>();
            this.Basic_NewsCategory = new HashSet<Basic_NewsCategory>();
            this.Basic_Specialty = new HashSet<Basic_Specialty>();
            this.Basic_News = new HashSet<Basic_News>();
            this.Sys_Theme = new HashSet<Sys_Theme>();
            this.Content_Article = new HashSet<Content_Article>();
            this.Content_Category = new HashSet<Content_Category>();
            this.Sys_Menu = new HashSet<Sys_Menu>();
            this.Sys_School_PanelContent = new HashSet<Sys_School_PanelContent>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string LogoUrl { get; set; }
        public string WebSiteUrl { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
        public string EnglishName { get; set; }
    
        public virtual ICollection<Basic_Campus> Basic_Campus { get; set; }
        public virtual ICollection<Basic_DeviceToken> Basic_DeviceToken { get; set; }
        public virtual ICollection<Basic_Group> Basic_Group { get; set; }
        public virtual ICollection<Basic_GroupUser_Relationship> Basic_GroupUser_Relationship { get; set; }
        public virtual ICollection<Basic_OrganizeUser_Relationship> Basic_OrganizeUser_Relationship { get; set; }
        public virtual ICollection<Sys_Feature> Sys_Feature { get; set; }
        public virtual ICollection<Sys_Feature_Authority> Sys_Feature_Authority { get; set; }
        public virtual ICollection<Basic_TelephoneDirectory> Basic_TelephoneDirectory { get; set; }
        public virtual ICollection<Basic_NewsCategory> Basic_NewsCategory { get; set; }
        public virtual ICollection<Basic_Specialty> Basic_Specialty { get; set; }
        public virtual ICollection<Basic_News> Basic_News { get; set; }
        public virtual Message_SchoolKeys Message_SchoolKeys { get; set; }
        public virtual ICollection<Sys_Theme> Sys_Theme { get; set; }
        public virtual ICollection<Content_Article> Content_Article { get; set; }
        public virtual ICollection<Content_Category> Content_Category { get; set; }
        public virtual ICollection<Sys_Menu> Sys_Menu { get; set; }
        public virtual Sys_School_Extend Sys_School_Extend { get; set; }
        public virtual ICollection<Sys_School_PanelContent> Sys_School_PanelContent { get; set; }
    }
}
