//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User
    {
        public Sys_User()
        {
            this.Basic_DeviceToken = new HashSet<Basic_DeviceToken>();
            this.Basic_GroupUser_Relationship = new HashSet<Basic_GroupUser_Relationship>();
            this.Basic_OrganizeUser_Relationship = new HashSet<Basic_OrganizeUser_Relationship>();
            this.Sys_Role = new HashSet<Sys_Role>();
        }
    
        public string ID { get; set; }
        public string SchoolID { get; set; }
        public string LoginID { get; set; }
        public string UserName { get; set; }
        public string UserAccount { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
        public string HeaderImage { get; set; }
        public string QRCode { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
    
        public virtual ICollection<Basic_DeviceToken> Basic_DeviceToken { get; set; }
        public virtual ICollection<Basic_GroupUser_Relationship> Basic_GroupUser_Relationship { get; set; }
        public virtual ICollection<Basic_OrganizeUser_Relationship> Basic_OrganizeUser_Relationship { get; set; }
        public virtual Basic_Student Basic_Student { get; set; }
        public virtual ICollection<Sys_Role> Sys_Role { get; set; }
        public virtual Basic_TeacherInfo Basic_TeacherInfo { get; set; }
    }
}
