//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Feature
    {
        public Sys_Feature()
        {
            this.Sys_Feature_Authority = new HashSet<Sys_Feature_Authority>();
        }
    
        public string FeatureID { get; set; }
        public string SchoolID { get; set; }
        public string FeatureName { get; set; }
        public string FeatureIcon { get; set; }
        public string FeatureUrl { get; set; }
        public int FeatureType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
    
        public virtual ICollection<Sys_Feature_Authority> Sys_Feature_Authority { get; set; }
        public virtual Sys_School Sys_School { get; set; }
    }
}
